### ISSUE TITLE
How to Perform the Calibration?

### ISSUE THREAD

**Issue by FilipeLopesPires** [DarienBrito/TDAzureMerger#3]
Hello @DarienBrito ,

I am trying to calibrate multiple azure kinects using TDAzureMerger.
I have installed TouchDesigner and added your Open3D version to the path you suggest in the README.

With DemoCalibration.4.toe opened, I changed the sensor IDs to my Azure Kinects' and updated the AzureCalibration container configuration on project1.
Below I provide some screenshots of my setup.

![project1-configuration](https://user-images.githubusercontent.com/32246849/113693635-b2a85780-96c6-11eb-9e98-c10bc44429d7.png)
![project1-AzureCalibration](https://user-images.githubusercontent.com/32246849/113693076-1ed68b80-96c6-11eb-9081-81fc4bcfdac4.png)
![project1-Inputs](https://user-images.githubusercontent.com/32246849/113693078-2007b880-96c6-11eb-8173-46a9f7018f02.png)

I have tried using the "calibrate" operation without success, I am really guessing here...
Could you provide some guidance on how to proceed with the calibration of the 3 Azure Kinects connected?

**Comment by DarienBrito** [comment]
Hi Filipe, you do not need to assign ID's manually, you can simple use the pair parameter after pressing on "Gather kinects". You can see how to use it in the following link:

https://vimeo.com/501525725

**Comment by FilipeLopesPires** [comment]
Hello Darien,

Only now I was able to work with TDAzureMerger again. Thank you for providing the tutorial. 
When I enable the "Use player for calibration" parameter on the Calibration tab, the Geometry named geo_pc on "/project1/AzureCalibration/World" raises an error:
> Error: All OPs must generate the same number of instances (have the same length).

This prevents me from continuing with the calibration process... Do you know what might be causing this?

**Comment by DarienBrito** [comment]
That will occur if your input Kinect textures have different dimensions. Make sure that your Kinect cameras all have the same resolutions and are working, else you will get errors. Do note that if you have an RTXxx series graphics card you need to download the latest TouchDesigner version, since those series use a different CUDA library, which has been updated in the latest stable build of TD.

**Comment by FilipeLopesPires** [comment]
The dimensions were correct, but updating TouchDesigner did the trick. Thank you very much Darien, it now works!
But let me ask one more thing: you mention that if kinects have an angle greater than 90º it will not work; but what about a configuration of 3 azure kinects, each at an angle of 90º (meaning that 2 of them will be in opposite directions)? isn't it possible to calibrate with TDAzureMerger by aligning pairs 1-2 and then 2-3?

**Comment by DarienBrito** [comment]
Hi Filipe. Yes, in theory, that should be possible. I have done something like that myself once but I used "intermediate matrices", meaning that I took intermediate positions between the points to be able to move the Kinects to such an arrangement.
