### ISSUE TITLE
Script Error 

### ISSUE THREAD

**Issue by samuelshea** [DarienBrito/TDAzureMerger#6]
Hey @DarienBrito 

Im really excited about the possibility of using your tool!

I installed it and i'm getting an error. The camera ID's are being recognized on the configuration tab after pulsing, those Ids are not being imported into the calibration tab however so the calibrate pulse and refine pulse are not functional.

Inside of the AzureCalibration bin i'm receiving this error:
![IMG_2358 2](https://user-images.githubusercontent.com/105174403/167314767-6f4af063-ea2a-485d-a9b9-b0582c6fc1b2.jpg)

I'm running TD under windows 10 with Commercial license i purchased this week, so assuming the most recent version. 

Id love to get this usp and running for a big art install i'm doing in Mexico next weekend.

thanks for you help!

Sam

**Comment by DarienBrito** [comment]
Hi Sam,

Apologies for late reply! I'm sorry I saw your message so late, I hope the install in Mexico went well!
The error seems to be related to the open3D library not being recognized. Latest versions of that lib may not work, so you need to use a specific one I provide with the package:

The repository contains version 0.11.0, so you can use that directly by copying it to your TouchDesigner site packages folder, usually in a path like this:

C:\Program Files\Derivative\TouchDesigner.2020.28110\bin\Lib\site-packages

Does that solve the issue?

Best,
Darien

**Comment by DarienBrito** [comment]
Hi Sam, 

Just in case, the tool has been just updated to latest. That may solve your issue.
