### ISSUE TITLE
Calibration not

### ISSUE THREAD

**Issue by khaleepha007** [DarienBrito/TDAzureMerger#9]
Hello Darien, really impressive. 
i am currently using non-commercial touch designer  to run your program with two azure Kinect on a  NVida 3060Ti  GeForce RTX and I followed the instructions you provide. But the calibration is not working.

**Comment by DarienBrito** [comment]
Latest TD version is not compatible with the open3D version in the package. I'm working on updating the versions. Will upload that to the repository no later than this week.

**Comment by khaleepha007** [comment]
Thank you very much 

Kabir Ahmed Rufai II

**Comment by DarienBrito** [comment]
Updated. Please try with latest build in this repo

**Comment by khaleepha007** [comment]
Thank you Darien. I have a quick question. How do I cite your work if I use in my research?Regards Kabir Ahmed Rufai IIOn 1 Nov 2022, at 23:46, Darien ***@***.***> wrote:﻿
Closed #9 as completed.

**Comment by DarienBrito** [comment]
Oh, maybe you can cite it as something like:

TDAzureMerger: A TouchDesigner component to merge point clouds from Kinect Azure devices. v0.2.0, Darien Brito, 2020-2022.

**Comment by khaleepha007** [comment]
Thank you Regards Kabir Ahmed Rufai IIOn 2 Nov 2022, at 00:14, Darien ***@***.***> wrote:﻿
Oh, maybe you can cite it as something like:
TDAzureMerger: A TouchDesigner component to merge point clouds from Kinect Azure devices. v0.2.0, Darien Brito, 2020-2022.
